name: Permission check
on:
  pull_request_target:
    paths:
      - '**/run'
      - '**/finish'
      - '**/check'
      - 'root/migrations/*'

jobs:
  permission_check:
    uses: chukysoria/workflows/.github/workflows/init-svc-executable-permissions.yml@e6782c2fc4a5c686a4f937ef850ca3860c712ea4 # v1.1.10
